### PR TITLE
Add Gazetteer Postgres example

### PR DESCRIPTION
**Pull request by jeancochrane**
# Overview

Add a new Gazetteer example to perform static matching backed by a Postgres database with updates.

In addition, containerize the Gazetteer examples.

## Notes

A requirement of this example is to support Dedupe 1.x. Once this PR is approved and merged, and confirmed to work for the folks who requested it, I'll port the example to Dedupe 2.x.

## Testing instructions

* View the [Gazetteer README](https://github.com/dedupeio/dedupe-examples/blob/jfc/gazetteer-pgsql-example/gazetteer_example/README.md)
* Follow the installation instructions and confirm you can build the container images
* Follow the usage instructions and confirm you can run each script

### CODE REVIEW

**Comment by jeancochrane** [comment]
@fgregg This PR overrides the `index()` and `_blockData()` methods to use a database backend. I decided to override `_blockData()` because it seemed like the key piece of both `match()` and `threshold()` that needed to be refactored to using the database, but let me know if there are other pieces I missed. Curious to get your high-level take before I wire it up to make sure it runs.

**Comment by fgregg** [comment]
looks very good.

**Comment by jeancochrane** [comment]
Alright, this should be ready for another look @fgregg. Since we have to support both the 1.x and 2.x APIs in this example directory I went ahead and containerized them.

**Comment by fgregg** [comment]
Let's just keep this dedupe 1.10.

We can bring a dedupe 2.0 version into master, and let's not do Docker, since don't have that with any of the other examples.

**Comment by jeancochrane** [comment]
@fgregg The issue is that the existing Gazetteer example is dedupe 2.x, but we need to support dedupe 1.x in the new example. However, I'm trying to bootstrap on the existing code sample so that we don't have to duplicate all of the training code in the new example using the 1.x API.

I think our options here are:

- Duplicate the training code from the existing example in the 1.x example
- Keep the Docker environment
- Provide detailed setup instructions for managing different virtualenvs for running each script

**Comment by fgregg** [comment]
Got it! Thank you for helping me see that context.

I'd recommend: Duplicate the training code from the existing example in the 1.x example

**Comment by jeancochrane** [comment]
Makes sense! I'll go ahead with that then.

**Comment by jeancochrane** [comment]
@fgregg I stripped out the Docker environment, updated the instructions to explain how to manage environments and run scripts with a local Python installation, and updated the Postgres script to be fully independent. I also added some more explanatory comments to the `StaticDatabaseGazetteer` class. Let me know how everything looks to you.

How would you like to handle bringing this into master? I don't love having two examples using two different versions of dedupe. The clearest path to me seems to be to bring this into master, share it via a commit ID with the folks who requested it, and then bring in a new PR that updates to 2.0 once we've confirmed that it worked for them. We could also consider having a long-lived branch to share with them, but I don't like the maintenance burden that that implies.

**Pull request merged**
